config/routes.rb
EligeTuEscuela::Application.routes.draw do

  resources :schools, only: :show do
    post :filter, on: :collection
  end

  get :search, to: 'schools#search', as: :search
  root 'pages#home'
end

app/models/school.rb
class School < ActiveRecord::Base
  SEMAPHORE_STATUSES = ['Excelente', 'Bien', 'De panzazo', 'Reprobado',
                        'Escuela no confiable']

  reverse_geocoded_by :latitude, :longitude
  serialize :enlace_results
  serialize :contact_info, Hash

  def full_address
    address = "#{self.address} #{self.suburb} "
    address << "entre #{self.between_street_1} " unless self.between_street_1.blank?
    unless between_street_2.blank?
      address << (self.between_street_1.blank? ? "entre " : "y ")
      address << self.between_street_2
    end
    address << ", Culiacán, Sinaloa. #{self.zip_code}"
  end

  def preregistered_students_count
    self.max_availability - self.availability
  end

  def contact_name
    self.contact_info[:name]
  end

  def contact_position
    self.contact_info[:position]
  end

  def contact_hours
    self.contact_info[:schedule]
  end

  def availability_data_valid?
    self.max_availability > 0
  end

  def self.count_for_similar_to(school)
    School.where(grade: school.grade).count
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @school_searcher = SchoolSearcher.new
  end

end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController

  before_filter :get_school, only: [:show]
  add_breadcrumb I18n.t('breadcrumb.home'), :root_path

  def search
    @school_searcher = SchoolSearcher.new(params[:school_searcher])
    if @school_searcher.valid?
      persist_search_info_in_session
      @home = @school_searcher.origin_coordinates
      @schools = @school_searcher.schools_by_distance
    else
      render 'pages/home'
    end
  end

  def show
  end

  def filter
    @school_searcher = SchoolSearcher.new(extract_search_info_from_session)
    if @school_searcher.valid? && params[:school_filters].present?
      @schools = @school_searcher.schools_by_distance(params[:school_filters])
      render json: @schools.to_json(methods: [:full_address])
    else
      if @school_searcher.valid?
        render json: t('errors.messages.missing_filters'), status: :unprocessable_entity
      else
        render json: t('errors.messages.invalid_filter_search'), status: :unprocessable_entity
      end
    end
  end

  private

  def persist_search_info_in_session
    session[:school_search] = @school_searcher.serialize_for_session
  end

  def extract_search_info_from_session
    JSON.parse(session[:school_search])
  end

  def get_school
    @school ||= School.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def errors_on_resource_for_field(resource, field)
    unless resource.errors[field].empty?
      content_tag :div, resource.errors[field].join('<br/> ').html_safe, class: 'errors-form'
    end
  end

end

app/helpers/schools_helper.rb
module SchoolsHelper
  def marker_info_for_schools(schools)
    schools.to_json(only: [:latitude, :longitude, :name], :methods => [:full_address])
  end

  def marker_info_for_coordinates(coordinates, name="")
    {latitude: coordinates[0], longitude: coordinates[1], name: name}.to_json
  end

  def school_educational_semaphore_list_el(school)
    School::SEMAPHORE_STATUSES.map do |status|
      if status == school.educational_semaphore
        content_tag(:li, status, class: 'check')
      else
        content_tag(:li, status)
      end
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Elige Tu Escuela</title>
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=#{ENV['GOOGLE_KEY']}&sensor=false" %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <link href='http://fonts.googleapis.com/css?family=PT+Sans:400,700,400italic|PT+Sans+Caption' rel='stylesheet' type='text/css'>


    <%= csrf_meta_tags %>
  </head>
  <body>

    <div id='wrap'>
      <nav class='container nav'>
        <%= link_to root_path, class: 'logo' do %>
          <%= image_tag 'logo-white.png', alt: 'Elige Tu Escuela' %>
        <% end%>
        <div class='pull-right'>
          <%= link_to nil, 'http://facebook.com', class: 'social fb' %>
          <%= link_to nil, 'http://twitter.com', class: 'social tt' %>
        </div>
      </nav>

      <div class="container">
        <%= yield %>
      </div><!-- /.container -->
    </div>

    <!-- footer -->

    <footer>
      <div class='container'>
        <p class='content'>
          Elige Tu Escuela <br />
          Copyright &copy; 2014 Elige Tu Escuela.
        </p>
        <%= image_tag 'logo-color.png', class: 'logo'%>
      </div>
    </footer>
    <!-- /footer -->

  </body>
</html>

app/views/pages/home.html.erb
<div class='welcome-box'>
  <h1 class='welcome-title'>
    <span class='bold-condensed'>¡BIENVENIDO!</span> <br/ >
    a las preinscripciones en escuelas de <span class='welcome-arrow'>Sinaloa</span></h1>
  <p>Elige Tu Escuela es una nueva aplicación para el Estado de Sinaloa que permite a padres de familia consultar</p>
</div>

<div class='step'>
  <h2 class='step-header'>
    <span class='step-line'> Paso 1: </span><br/>
    <span class='step-line'> Descubre tus escuelas</span>
  </h2>
  <p class='step-instructions'>El primer paso es encontrar tus escuelas cercanas con cupo disponible en las cuales tu hijo es elegible</p>
  <!-- Search form -->
  <div class='row'>
    <div class='col-md-8'>
      <div class='step-definition'>
        <p class='step-definition-title'>Completa el siguiente formulario</p>
        <div class='row'>
          <%= form_for @school_searcher, url: search_path, html: { class: "js-search-form-home search-form col-md-12", method: :get } do |f| %>
            <%= render partial: 'schools/form_search', locals: { f: f } %>
          <% end %>
        </div>
        <!-- /End search form -->
      </div>
    </div>
  </div>
</div>

<div class='step'>
  <h2 class='step-header'>
    <span class='step-line'>Paso 2:</span><br/>
    <span class='step-line'>Preinscripción</span>
  </h2>
  <p class='step-instructions'>Las preinscripciones inician el 4 de febrero.</p>
  <div class='row'>
    <div class='col-md-6'>
      <div class='step-definition'>
        <p class='step-definition-title'>El proceso es en 3 fases:</p>
        <div class='step-definition-content'>
          <ul class='step-definition-list'>
            <li><span class='list-indicator'>Fase 1</span> Estudiantes con hermanos en la escuela</li>
            <li><span class='list-indicator'>Fase 2</span> Cercanía a la escuela elegible</li>
            <li><span class='list-indicator'>Fase 3</span> Libre</li>
          </ul>
        </div>
      </div> <!-- End step definition -->
    </div>
  </div>
</div>

<div class='step'>
  <h2 class='step-header'>
    <span class='step-line'>Paso 3:</span><br/>
    <span class='step-line'>Inscripción</span>
  </h2>
  <p class='step-instructions'>Ten listos todos los papeles necesarios para inscribir oficialemente a tu hijo:</p>
  <div class='row'>
    <div class='col-md-6'>
      <div class='step-definition'>
        <p class='step-definition-title'>Entrega de documentos:</p>
        <div class='step-definition-content'>
          <ul class='step-definition-list'>
            <li><span class='list-indicator'>1</span> Acta de nacimiento</li>
            <li><span class='list-indicator'>2</span> Comprobante de domicilio</li>
            <li><span class='list-indicator'>3</span> 6 Fotografías a color tamaño infantil</li>
          </ul>
        </div>
      </div><!-- end step definition -->
    </div>
  </div>
</div>

<div class='step'>
  <h2 class='step-header'>
    <span class='step-line'>Paso 4:</span><br/>
    <span class='step-line'>¡A clases!</span>
  </h2>
  <div class='step-four'>
    <%= image_tag 'pencil-white.png', class: 'img-responsive' %>
    <div class='step-four-text'>
      <p class='big'>¡Listo para comenzar las clases!</p>
      <p>Para cualquier duda, contacta a tu director.</p>
    </div>
  </div>
</div>

app/views/schools/_form_search.html.erb
<div class='top-fields'>
  <div class='form-group col-md-6'>
      <%= f.text_field :street_and_number, placeholder: t('forms.search.address_placeholder'), class: 'form-control', required: true %>
      <%= errors_on_resource_for_field(@school_searcher, :street_and_number) %>
  </div>
  <div class='form-group col-md-6'>
      <%= f.text_field :suburb, placeholder: t('forms.search.suburb_placeholder'), class: 'form-control', required: true %>
      <%= errors_on_resource_for_field(@school_searcher, :suburb) %>
  </div>
</div>
<div class='lower-fields'>
  <div class='form-group col-md-4'>
    <%= f.text_field :zip_code, placeholder: t('forms.search.zip_code_placeholder'), class: 'form-control', required: true %>
    <%= errors_on_resource_for_field(@school_searcher, :zip_code) %>
  </div>
  <div class='form-group col-md-4'>
    <%= f.select :city, options_for_select(SchoolSearcher::CITIES, SchoolSearcher::CITIES.first), {}, class: 'form-control' %>
    <%= errors_on_resource_for_field(@school_searcher, :city) %>
  </div>
  <div class='form-group col-md-4'>
    <%= f.select :grade, options_for_select(SchoolSearcher::GRADES), {prompt: t('forms.search.grade')}, {class: 'form-control'}  %>
    <%= errors_on_resource_for_field(@school_searcher, :grade) %>
  </div>
</div>
<div class='col-md-12'>
  <%= f.button(type: 'submit', class: "btn btn-primary") do %>
    <%= t('helpers.search_school') %>
    <i class="glyphicon glyphicon-search"></i>
  <% end %>
</div>

app/views/schools/_form_search_inline.html.erb
<div class='form-group col-sm-3'>
  <%= f.text_field :street_and_number, placeholder: t('forms.search.address_placeholder'), class: 'form-control', required: true %>
  <%= errors_on_resource_for_field(@school_searcher, :street_and_number) %>
</div>
<div class='form-group col-sm-3'>
  <%= f.text_field :suburb, placeholder: t('forms.search.suburb_placeholder'), class: 'form-control', required: true %>
  <%= errors_on_resource_for_field(@school_searcher, :suburb) %>
</div>
<div class='form-group col-sm-2'>
  <%= f.text_field :zip_code, placeholder: t('forms.search.zip_code_placeholder'), class: 'form-control', required: true %>
  <%= errors_on_resource_for_field(@school_searcher, :zip_code) %>
</div>
<div class='form-group col-sm-2'>
  <%= f.select :city, options_for_select(SchoolSearcher::CITIES, SchoolSearcher::CITIES.first), {}, class: 'form-control' %>
  <%= errors_on_resource_for_field(@school_searcher, :city) %>
</div>
<div class='form-group col-sm-2'>
  <%= f.select :grade, options_for_select(SchoolSearcher::GRADES), {prompt: t('forms.search.grade')}, {class: 'form-control'}  %>
  <%= errors_on_resource_for_field(@school_searcher, :grade) %>
</div>
<div class='block-divider'>
  <div class='col-sm-4 col-sm-offset-4'>
    <%= f.button(type: 'submit', class: "btn btn-primary btn-block") do %>
      <%= t('helpers.search_school') %>
      <i class="glyphicon glyphicon-search"></i>
    <% end %>
  </div>
</div>

app/views/schools/search.html.erb
<%= render 'shared/breadcrumb_header' %>

<!-- Search form -->
<div class='block-wrapper l-bl-separation'>
  <div class='row'>
    <%= form_for @school_searcher, url: search_path, html: { class: "js-search-form-results col-md-12", method: :get } do |f| %>
      <%= render partial: 'schools/form_search_inline', locals: { f: f } %>
    <% end %>
  </div>
</div>
<!-- /End search form -->

<!-- MAP -->
<div id='map-wrapper' class='l-bl-separation'>
  <div class='map-container'>
    <div id='gmap' data-markers="<%= marker_info_for_schools(@schools) %>" data-home="<%= marker_info_for_coordinates(@home) %>"></div>
  </div>
</div>
<! -- END MAP -->

<div class='row'>
  <div class='col-md-3'>
    <div class='search-filters l-bl-separation'>
      <p class='search-filters-title'>Filtro de resultados:</p>
      <%= form_tag filter_schools_path, method: :post, id: 'filter_schools', class: 'js-filter-form', remote: true do %>
        <div class='search-filter-sec'>
          <p class='search-filter-sec-title'>Turno</p>
          <%= label_tag :shift, class: 'search-filter-option' do %>
            <%= check_box_tag 'school_filters[shift][]', t('forms.filters.morning') %>
            <%= t('forms.filters.morning') %>
          <% end%>
          <%= label_tag :shift, class: 'search-filter-option' do %>
            <%= check_box_tag 'school_filters[shift][]', t('forms.filters.evening') %>
            <%= t('forms.filters.evening') %>
          <% end%>
          <%= label_tag :shift, class: 'search-filter-option' do %>
            <%= check_box_tag 'school_filters[shift][]', t('forms.filters.night') %>
            <%= t('forms.filters.night') %>
          <% end%>
          <%= label_tag :shift, class: 'search-filter-option' do %>
            <%= check_box_tag 'school_filters[shift][]', t('forms.filters.mixed') %>
            <%= t('forms.filters.mixed') %>
          <% end%>
        </div>
        <div class='search-filter-submit'>
          <%= submit_tag t('helpers.filter'), class: 'btn btn-primary btn-block', data: {disable_with: t('helpers.filtering')} %>
        </div>
      <% end %>
    </div>
  </div>
  <div class='col-md-9'>
    <div class='table-responsive'>
      <table id='school-results' class='table table-custom'>
        <thead>
          <th>ID</th>
          <th>Nombre de la escuela</th>
          <th>Distancia</th>
          <th>Cupo Disponible</th>
          <th>Posición Municipal</th>
        </thead>
        <% @schools.each_with_index do | school, index | %>
          <tr>
            <td><%= index+1 %> </td>
            <td><%= link_to school.name, school_path(school), class: 'school-name' %> </td>
            <td><%= school.distance.round(2) %> km </td>
            <td><%= t('helpers.not_available') %> </td>
            <td><%= school.city_rank || t('helpers.not_available') %></td>
          </tr>
        <% end%>
      </table>
    </div>
  </div>
</div>

app/views/schools/show.html.erb
<%= render 'shared/breadcrumb_header' %>

<!-- SHOWCASE -->
<div class='school-showcase l-bl-separation'>
  <div class='school-showcase-pic' style="background-image: url(<%= asset_path('escuela_default.png') %>)"></div>
  <div class='school-showcase-wrapper'>
    <div class='step-title l-gallery-title'>
      <h1 class='step-line'><%= @school.name %></h1><br/>
      <p class='step-line'><%= @school.grade.upcase %> | <%= @school.shift.upcase%></p>
    </div>

    <div class='l-buttons-showcase'>
      <%= link_to t('.compare_schools').upcase,
        'http://www.mejoratuescuela.org/compara/',
        class: 'btn btn-primary l-sm-r-separation btn-lg' %>
      <%= link_to t('.preregister').upcase,
        'http://www.preinscripcionessinaloa.gob.mx/',
        class: 'btn btn-default btn-lg' %>
    </div>
  </div>

</div> <!-- END SHOWCASE -->

<!-- SCHOOL DESCRIPTION -->
<div class='gray-wrapper'>
  <div class='row'>
    <div class='col-md-8'>
      <div class='step-title l-bl-med-separation'>
        <h2 class='step-line'><%= t('.student_occupation') %></h2>
      </div>

      <div class='row l-bl-med-separation'>
        <div class='col-md-4'>
          <div class='school-stat'>
            <p class='school-stat-name'>Cupo Máximo</p>
            <p class='school-stat-value'>
              <% if @school.availability_data_valid? %>
                <%= "#{@school.max_availability} Alumnos" %>
              <% else %>
                <%=  t('helpers.not_available') %>
              <% end %>
            </p>
          </div>
        </div>
        <div class='col-md-4'>
          <div class='school-stat'>
            <p class='school-stat-name'>Cupo Actual</p>
            <p class='school-stat-value'>
              <% if @school.availability_data_valid? %>
                <%= "#{@school.preregistered_students_count} Alumnos" %>
              <% else %>
                <%=  t('helpers.not_available') %>
              <% end %>
            </p>
          </div>
        </div>
        <div class='col-md-4'>
          <div class='school-stat'>
            <p class='school-stat-name'>Lugares Disponibles</p>
            <p class='school-stat-value'>
              <% if @school.availability_data_valid? %>
                <%= "#{@school.availability} Alumnos" %>
              <% else %>
                <%=  t('helpers.not_available') %>
              <% end %>
            </p>
          </div>
        </div>
      </div>

      <div class='white-wrapper l-bl-med-separation'>
        <div id='gmap-school-show' data-lat="<%= @school.latitude %>" data-lng="<%= @school.longitude%>" class='l-bl-med-separation'>
        </div>
        <p><b>Dirección:</b> <%= @school.full_address %></p>
      </div>

      <div class='step'>
        <div class='step-definition'>
          <p class='step-definition-title step-definition-title-user'>Información de contacto</p>
          <div class='step-definition-content'>
            <ul class='step-definition-list'>
              <li class='indicator-right short'><%= @school.contact_name %><span class='list-indicator'><%= @school.contact_position%></span> </li>
              <li class='clearfix no-indicator'>
                <span>
                  <%= "Teléfono: #{number_to_phone(@school.phone_number)}" if @school.phone_number %>
                  <%= "Fax: #{number_to_phone(@school.fax)}" if @school.fax %>
                </span>
                <span class='pull-right'>Horarios de Atención: <%= @school.contact_hours %></span>
              </li>
              <li class='clearfix no-indicator'>
                <span class='pull-left'>
                  Página Web: <%= @school.web_page || t('helpers.not_available') %>
                </span>
                <span class='pull-right'>
                   Coreo electrónico: <%= @school.email || t('helpers.not_available') %>
                </span>
              </li>
            </ul>
          </div>
        </div> <!-- End step definition -->
      </div>
    </div>


    <div class='col-md-4'>
      <div class='rank l-bl-med-separation'>
        <% unless @school.city_rank.nil? %>
          <p class='rank-position'>
            <%= @school.city_rank %> LUGAR / DE <%= School.count_for_similar_to(@school)%>
          </p>
          <p>Posición en ciudad</p>
        <% end %>
        <p>No hay datos sobre su posición en la ciudad</p>
      </div>

      <div class='properties'>
        <ul class='l-bl-med-separation'>
          <li class='property-header'>SEMÁFORO EDUCATIVO</li>
          <% school_educational_semaphore_list_el(@school).each do |li| %>
            <%= li %>
          <% end %>
        </ul>
        <ul class='l-bl-med-separation'>
          <li class='property-header'>PROGRAMAS</li>
          <li class='check'>Escuela Segura</li>
          <li class='check'>Escuela de calidad</li>
          <li class='check'>Tiempo completo</li>
        </ul>
      </div>
    </div> <!-- END SIDEBAR -->
  </div>
</div><!-- -->

app/views/shared/_breadcrumb_header.html.erb
<div class='welcome-box l-bl-separation'>
  <h2 class='welcome-title welcome-title-inline'>
    <span class='bold-condensed'>BIENVENIDO</span>
    a las preinscripciones en escuelas de <span class='welcome-arrow'>Sinaloa</span></h2>
</div>

<ol class="breadcrumbs l-bl-separation">
  <li class='beginning'></li>
  <%= render_breadcrumbs tag: :li%>
</ol>